### ISSUE TITLE
OpenSearch compatibility issue

### ISSUE THREAD

**Issue by M-Razavi** [senacor/elasticsearch-evolution#220]
I got the "Elasticsearch version 6 or more is required" when I wanted to use OpenSearch. Is there any plan to support OpenSearch directly?

**Comment by xtermi2** [comment]
How is your environment? OpenSearch Version, Spring Boot, ...?
OpenSearch 2.6.0, 2.5.0, 2.4.1, 1.3.9 should be work fine, that versions are tested.

**Comment by M-Razavi** [comment]
I'm using SpringBoot 2.7.7 with OpenSearch 1.1.0 in a dockerized environment. before using the **elasticsearch evolution** I had only OpenSearch dependency on my project but for using evolution, I had to add ElasticSearch dependencies. Now I use `org.elasticsearch.client.RestClien`t for evolution and `org.opensearch.client.RestHighLevelClient` for other usages in my app, otherwise I get this error. 

`ElasticsearchException[Elasticsearch version 6 or more is required]
	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2701)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105)`
	
I don't want to have such messy dependency and ElasticSearch dependencies on my project.

**Comment by xtermi2** [comment]
#198 will address this
